spring:
  datasource:
    url: jdbc:postgresql://lallah.db.elephantsql.com/svubttgr
    username: svubttgr
    password: EzddxO6EK9RHnqj22Y-nxPS8jo2mjlXA
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mvc:
    dispatch-options-request: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # a day
      refresh-token:
        expiration: 604800000 # 7 days